title: Trapped
description: A networked multiplayer game built for UW Bothell's Game Development class.
url: https://lizzy.wiki/trapped

remote_theme: "etcadinfinitum/mixtape"
plugins:
  - jemoji

exclude: [node]

# for buttons in header
show_downloads: true

collections:
  posts:
    permalink: "/log/:year/:month/:day/:title/"
    output: true

header_links:
  - url: https://github.com/etcadinfinitum/trapped
    name: View Source Code
  - url: https://lizzy.wiki/trapped/release/final_demo/              # This needs to be updated regularly
    name: Play Now

nav_links:
  - url: /
    name: Home
  - url: /log
    name: Dev Log
  - url: /about
    name: About
